# Generated by Django 4.2.11 on 2024-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
