# Generated by Django 4.2.11 on 2024-04-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='About',
        ),
    ]
